export const leadTableData = [
  {
    ownerName: "Dilshad Shaikh",
    businessName: "Scissor Enterprise",
    mobile: "7046158373",
    salesExecutive: "Rutu Patel",
    email: "dilshadshaikh@gmail.com",
    city: "Ahmedabad",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "03/12/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Aashish Patel",
    businessName: "Mahadev Electronics",
    mobile: "9624890992",
    salesExecutive: "Rutu Patel",
    email: "ashishpatel@gmail.com",
    city: "Mumbai",
    leadSource: "Linkedin",
    leadType: "Cold",
    currentStatus: "New",
    createdDate: "03/13/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Rakesh Jha",
    businessName: "Levere Traders",
    mobile: "7874329308",
    salesExecutive: "Rutu Patel",
    email: "rakeshjha@gmail.com",
    city: "Delhi",
    leadSource: "Linkedin",
    leadType: "Hot",
    currentStatus: "New",
    createdDate: "03/14/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Krishna Shah",
    businessName: "Krishna Beauty Traders",
    mobile: "7041853241",
    salesExecutive: "Rutu Patel",
    email: "krishna@beautyTraders.com",
    city: "Chennai",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "03/15/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "B. M Agrawal",
    businessName: "Bahu Rani",
    mobile: "9586490300",
    salesExecutive: "Rutu Patel",
    email: "b.m@hotmail.com",
    city: "Surat",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "03/16/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Jinesh Gandhi",
    businessName: "Jin Mobile",
    mobile: "7433033884",
    salesExecutive: "Rutu Patel",
    email: "jinesh.g@gmail.com",
    city: "Ahmedabad",
    leadSource: "Linkedin",
    leadType: "Hot",
    currentStatus: "New",
    createdDate: "03/17/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Abhishek Jain",
    businessName: "New Aabhushan Jewellers",
    mobile: "9904466814",
    salesExecutive: "Rutu Patel",
    email: "abhishekjain@gmail.com",
    city: "Pune",
    leadSource: "Facebook",
    leadType: "Cold",
    currentStatus: "Contacted",
    createdDate: "03/18/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Parvesh Khan",
    businessName: "Central Bakery",
    mobile: "7777991333",
    salesExecutive: "Rutu Patel",
    email: "parveshkhan@gmail.com",
    city: "Jaipur",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "03/19/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Anil Sharma",
    businessName: "De Ramas Multi Cuisine Restaurant",
    mobile: "8980999666",
    salesExecutive: "Rutu Patel",
    email: "anilsharma@gmail.com",
    city: "Mohali",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "03/20/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Mohammad Salman",
    businessName: "Cut & Care Unisex Enterprise",
    mobile: "9099662197",
    salesExecutive: "Rutu Patel",
    email: "mohammadsalman@gmail.com",
    city: "Rajkot",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "03/21/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Gautam Yadav",
    businessName: "Posh Boutique",
    mobile: "9375980086",
    salesExecutive: "Rutu Patel",
    email: "gautam@gmail.com",
    city: "Lucknow",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "03/22/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Dhaval Shethna",
    businessName: "Hemali Traders",
    mobile: "2612668635",
    salesExecutive: "Rutu Patel",
    email: "dhavalshethna@hotmail.com",
    city: "Ahmedabad",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "03/23/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sahil Patel",
    businessName: "Sonam Enterprise",
    mobile: "9664907862",
    salesExecutive: "Rutu Patel",
    email: "sahilpatel@gmail.com",
    city: "Mumbai",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "03/24/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Hasmukhbhai",
    businessName: "Mahalaxmi Jewellers",
    mobile: "9427392303",
    salesExecutive: "Rutu Patel",
    email: "hasmukhbhai@hotmail.com",
    city: "Delhi",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "03/25/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Irfan Seth",
    businessName: "Style Traders",
    mobile: "9687262631",
    salesExecutive: "Rutu Patel",
    email: "irfanseth@gmail.com",
    city: "Chennai",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "03/26/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Shivam Bhai",
    businessName: "Tggs Enterprise",
    mobile: "9925545625",
    salesExecutive: "Rutu Patel",
    email: "shivambhai@gmail.com",
    city: "Surat",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "03/27/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Jay Bhalani",
    businessName: "Excellent Family Enterprise",
    mobile: "9978340906",
    salesExecutive: "Rutu Patel",
    email: "jaybhalani@gmail.com",
    city: "Ahmedabad",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "03/28/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Keval Kapoor",
    businessName: "S K Enterprise",
    mobile: "8261818181",
    salesExecutive: "Rutu Patel",
    email: "kevalkapoor@gmail.com",
    city: "Pune",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "03/29/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Aarti Mahapat",
    businessName: "Blossom Spa And Enterprise",
    mobile: "9824904040",
    salesExecutive: "Rutu Patel",
    email: "aartimahapat@hotmail.com",
    city: "Jaipur",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "03/30/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Jagdish Kohli",
    businessName: "Alessiya Enterprise",
    mobile: "9427894795",
    salesExecutive: "Rutu Patel",
    email: "jagdishkohli@gmail.com",
    city: "Mohali",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "03/31/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Giri Rajan",
    businessName: "Aroma Wellness",
    mobile: "8980927904",
    salesExecutive: "Rutu Patel",
    email: "girirajan@gmail.com",
    city: "Rajkot",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "04/01/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Mahendra  Patel",
    businessName: "Aashapura Mobile",
    mobile: "9714924104",
    salesExecutive: "Rutu Patel",
    email: "mahendrapatel@hotmail.com",
    city: "Lucknow",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "04/02/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Rajan Rahane",
    businessName: "Hp Technosoft",
    mobile: "7990149371",
    salesExecutive: "Rutu Patel",
    email: "rajanrahane@gmail.com",
    city: "Delhi",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "04/03/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Nitin Ahuja",
    businessName: "Shivam Solutions",
    mobile: "9727399510",
    salesExecutive: "Rutu Patel",
    email: "nitinahuja@gmail.com",
    city: "Ahmedabad",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "04/04/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Tanisha Yadav",
    businessName: "Pixie Enterprise",
    mobile: "9723350009",
    salesExecutive: "Rutu Patel",
    email: "tanishayadav@hotmail.com",
    city: "Pune",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "04/05/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sandip Ichani",
    businessName: "Bhuvneshwar Jewellers",
    mobile: "8490048366",
    salesExecutive: "Rutu Patel",
    email: "sandipichani@gmail.com",
    city: "Chennai",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "04/06/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Shubham",
    businessName: "Sanskruti",
    mobile: "8780520586",
    salesExecutive: "Rutu Patel",
    email: "shubham1212@gmail.com",
    city: "Ahmedabad",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "04/07/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Kamlesh Bhai",
    businessName: "Maa Optics",
    mobile: "9913640291",
    salesExecutive: "Rutu Patel",
    email: "kamlesh bhai1312@gmail.com",
    city: "Mumbai",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "04/08/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Dipenbhai",
    businessName: "Hetvi The Mobile Shop",
    mobile: "7041411122",
    salesExecutive: "Rutu Patel",
    email: "dipenbhai1412@gmail.com",
    city: "Delhi",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "04/09/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Naishav Shah",
    businessName: "Chirag Gold",
    mobile: "8780545425",
    salesExecutive: "Rutu Patel",
    email: "naishav shah1512@gmail.com",
    city: "Chennai",
    leadSource: "IndiaMART",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "04/10/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Divya",
    businessName: "Coco International Enterprise (Sarathe)",
    mobile: "9879489771",
    salesExecutive: "Rutu Patel",
    email: "divya1612@gmail.com",
    city: "Surat",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "04/11/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Ketan Bhai",
    businessName: "Kre8 Enterprise",
    mobile: "9924586777",
    salesExecutive: "Rutu Patel",
    email: "ketan bhai1712@gmail.com",
    city: "Ahmedabad",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "04/12/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Kamplesh",
    businessName: "Jain Mobile",
    mobile: "9427811119",
    salesExecutive: "Rutu Patel",
    email: "kamplesh1812@gmail.com",
    city: "Pune",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "04/13/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Abhi",
    businessName: "Advance Professional Family Saloon",
    mobile: "7778889965",
    salesExecutive: "Rutu Patel",
    email: "abhi1912@gmail.com",
    city: "Jaipur",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "04/14/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Ishita Patel",
    businessName: "Cos Clash Of Scissors",
    mobile: "9924968852",
    salesExecutive: "Rutu Patel",
    email: "ishita patel2012@gmail.com",
    city: "Mohali",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "04/15/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Dharmesh",
    businessName: "Khodiyar Fabrics",
    mobile: "9925828010",
    salesExecutive: "Rutu Patel",
    email: "dharmesh2112@gmail.com",
    city: "Rajkot",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "04/16/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Priteah Bhai",
    businessName: "Shop & Wear",
    mobile: "9925619787",
    salesExecutive: "Rutu Patel",
    email: "priteah bhai2212@gmail.com",
    city: "Lucknow",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "04/17/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Honey And Vishwas",
    businessName: "Connections",
    mobile: "8625003047",
    salesExecutive: "Rutu Patel",
    email: "honey and vishwas2312@gmail.com",
    city: "Ahmedabad",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "04/18/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Jabbar",
    businessName: "4 U Enterprise",
    mobile: "9737717213",
    salesExecutive: "Rutu Patel",
    email: "jabbar2412@gmail.com",
    city: "Mumbai",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "04/19/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Pooja Jain",
    businessName: "The Beauty Bar",
    mobile: "7567561960",
    salesExecutive: "Rutu Patel",
    email: "pooja jain2512@gmail.com",
    city: "Delhi",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "04/20/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Kesu Patel",
    businessName: "New Agarwal Suites",
    mobile: "9825209310",
    salesExecutive: "Rutu Patel",
    email: "kesu patel2612@gmail.com",
    city: "Chennai",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "04/21/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Anita",
    businessName: "Shree Rang Hair & Beauty Enterprise (Western Arena Adajan)",
    mobile: "9726257467",
    salesExecutive: "Rutu Patel",
    email: "anita2712@gmail.com",
    city: "Surat",
    leadSource: "IndiaMART",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "04/22/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Rakesh Bhai",
    businessName: "Rushabh Mobile",
    mobile: "9824066774",
    salesExecutive: "Rutu Patel",
    email: "rakesh bhai2812@gmail.com",
    city: "Ahmedabad",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "04/23/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Harishbhai",
    businessName: "Dirty Looks",
    mobile: "9510848412",
    salesExecutive: "Rutu Patel",
    email: "harishbhai2912@gmail.com",
    city: "Pune",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "04/24/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Bhavesh",
    businessName: "Reflection Enterprise",
    mobile: "7016978789",
    salesExecutive: "Rutu Patel",
    email: "bhavesh3012@gmail.com",
    city: "Jaipur",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "04/25/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Rohit Bhai",
    businessName: "Navkar World",
    mobile: "9898245236",
    salesExecutive: "Rutu Patel",
    email: "rohit bhai3112@gmail.com",
    city: "Mohali",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "04/26/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Dashrath Chauhan",
    businessName: "Shreeji Enterprise",
    mobile: "9426572856",
    salesExecutive: "Rutu Patel",
    email: "dashrath chauhan3212@gmail.com",
    city: "Rajkot",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "04/27/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sunny Bhai",
    businessName: "The Gentleman Enterprise",
    mobile: "9727419254",
    salesExecutive: "Rutu Patel",
    email: "sunny bhai3312@gmail.com",
    city: "Lucknow",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "04/28/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Bhupendra",
    businessName: "Kv Fashion",
    mobile: "9724345184",
    salesExecutive: "Rutu Patel",
    email: "bhupendra3412@gmail.com",
    city: "Delhi",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "04/29/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Krina",
    businessName: "Krina Patel",
    mobile: "9879304056",
    salesExecutive: "Rutu Patel",
    email: "krina3512@gmail.com",
    city: "Ahmedabad",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "04/30/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Jitender Bhai",
    businessName: "Nayan Optical",
    mobile: "8000008065",
    salesExecutive: "Rutu Patel",
    email: "jitender bhai3612@gmail.com",
    city: "Pune",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "05/01/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Jainam",
    businessName: "Fashion Adda",
    mobile: "9429048673",
    salesExecutive: "Rutu Patel",
    email: "jainam3712@gmail.com",
    city: "Chennai",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "05/02/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Bhagirath",
    businessName: "The Family Shop",
    mobile: "9722343433",
    salesExecutive: "Rutu Patel",
    email: "bhagirath3812@gmail.com",
    city: "Pune",
    leadSource: "IndiaMART",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "05/03/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Dashrath Bhai",
    businessName: "Janta Jwellers",
    mobile: "9067336362",
    salesExecutive: "Rutu Patel",
    email: "dashrath bhai3912@gmail.com",
    city: "Nagpur",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "05/04/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Asif Bhai",
    businessName: "Fame Opics",
    mobile: "7383180471",
    salesExecutive: "Rutu Patel",
    email: "asif bhai4012@gmail.com",
    city: "Nashik",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "05/05/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sunny Bhai",
    businessName: "Sd Enterprise",
    mobile: "7043167324",
    salesExecutive: "Rutu Patel",
    email: "sunny bhai4112@gmail.com",
    city: "Aurangabad",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "05/06/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Rohit Bhai",
    businessName: "Rachna Mobile",
    mobile: "9913210217",
    salesExecutive: "Rutu Patel",
    email: "rohit bhai4212@gmail.com",
    city: "Mumbai",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "05/07/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Gaurav Manochia",
    businessName: "Gurukripa Kurties",
    mobile: "9512811569",
    salesExecutive: "Rutu Patel",
    email: "gaurav manochia4312@gmail.com",
    city: "Dombivli",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "05/08/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sunny Bhai",
    businessName: "Champak Communication",
    mobile: "9276857771",
    salesExecutive: "Rutu Patel",
    email: "sunny bhai4412@gmail.com",
    city: "Sahada",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "05/09/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Gunjan And Sandeep",
    businessName: "Snowera",
    mobile: "9327158858",
    salesExecutive: "Rutu Patel",
    email: "gunjan and sandeep4512@gmail.com",
    city: "Jamner",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "05/10/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sanjay",
    businessName: "Royal Hair Line",
    mobile: "8000293214",
    salesExecutive: "Rutu Patel",
    email: "sanjay4612@gmail.com",
    city: "Yavatmal",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "05/11/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Furkan (Ekta)",
    businessName: "Style",
    mobile: "9978685976",
    salesExecutive: "Rutu Patel",
    email: "furkan (ekta)4712@gmail.com",
    city: "Taloda",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "05/12/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Rudra Bhai",
    businessName: "Rudra Mobile",
    mobile: "9824882256",
    salesExecutive: "Rutu Patel",
    email: "rudra bhai4812@gmail.com",
    city: "Hingoli",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "05/13/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Rakesh Maisuriya",
    businessName: "S Enterprise ( Palsana )",
    mobile: "9898960104",
    salesExecutive: "Rutu Patel",
    email: "rakesh maisuriya4912@gmail.com",
    city: "Satara",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "05/14/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Praful",
    businessName: "Acme",
    mobile: "9426434301",
    salesExecutive: "Rutu Patel",
    email: "praful5012@gmail.com",
    city: "Amravati",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "05/15/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Dilip Mittle Ultimate",
    businessName: "Dilip Ent",
    mobile: "9825205530",
    salesExecutive: "Rutu Patel",
    email: "dilip mittle ultimate5112@gmail.com",
    city: "Osmanabad",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "05/16/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Mahavir",
    businessName: "Crystal Unisex Enterprise ( Navsari)",
    mobile: "9152724544",
    salesExecutive: "Rutu Patel",
    email: "mahavir5212@gmail.com",
    city: "Pandharpur",
    leadSource: "IndiaMART",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "05/17/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Hiteshbhai",
    businessName: "Shree Collection Mobile",
    mobile: "8866197974",
    salesExecutive: "Rutu Patel",
    email: "hiteshbhai5312@gmail.com",
    city: "Kavathe Mahankal",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "05/18/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Meena Beb",
    businessName: "Meena Beauty Parlour",
    mobile: "9913334898",
    salesExecutive: "Rutu Patel",
    email: "meena beb5412@gmail.com",
    city: "Thane",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "05/19/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Chetan Bhai",
    businessName: "Khodiyar Fashion",
    mobile: "9624912918",
    salesExecutive: "Rutu Patel",
    email: "chetan bhai5512@gmail.com",
    city: "Delhi",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "05/20/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Manisha",
    businessName: "Style",
    mobile: "8141411292",
    salesExecutive: "Rutu Patel",
    email: "manisha5612@gmail.com",
    city: "Surat",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "05/21/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Jayesh Bhai",
    businessName: "Beblly",
    mobile: "9601291324",
    salesExecutive: "Rutu Patel",
    email: "jayesh bhai5712@gmail.com",
    city: "Pune",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "05/22/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Gaurangbhai",
    businessName: "Navkar Communication",
    mobile: "9824008564",
    salesExecutive: "Rutu Patel",
    email: "gaurangbhai5812@gmail.com",
    city: "Nagpur",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "05/23/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Nilesh Patel",
    businessName: "Gayatri Electronics",
    mobile: "9974707333",
    salesExecutive: "Rutu Patel",
    email: "nilesh patel5912@gmail.com",
    city: "Nashik",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "05/24/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Herikbhai",
    businessName: "Advance Professional Enterprise (Parvat Patiya)",
    mobile: "9879499007",
    salesExecutive: "Rutu Patel",
    email: "herikbhai6012@gmail.com",
    city: "Aurangabad",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "05/25/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Nehal",
    businessName: "Arihant Jewellery",
    mobile: "9825520030",
    salesExecutive: "Rutu Patel",
    email: "nehal6112@gmail.com",
    city: "Mumbai",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "05/26/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Priyashri",
    businessName: "Golden Glitz",
    mobile: "9228584164",
    salesExecutive: "Rutu Patel",
    email: "priyashri6212@gmail.com",
    city: "Dombivli",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "05/27/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Anish Bhai",
    businessName: "Aftab Beauty Unisex Enterprise ( Navsari )",
    mobile: "9825739950",
    salesExecutive: "Rutu Patel",
    email: "anish bhai6312@gmail.com",
    city: "Sahada",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "05/28/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Abc",
    businessName: "Javed Habib New City Light",
    mobile: "7096227774",
    salesExecutive: "Rutu Patel",
    email: "abc6412@gmail.com",
    city: "Jamner",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "05/29/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Suresh Prajapati",
    businessName: "Rn Computer",
    mobile: "9913370154",
    salesExecutive: "Rutu Patel",
    email: "suresh prajapati6512@gmail.com",
    city: "Yavatmal",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "05/30/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sailesh Bhai",
    businessName: "Chashma Ghar( Mumbai)",
    mobile: "9320745262",
    salesExecutive: "Rutu Patel",
    email: "sailesh bhai6612@gmail.com",
    city: "Taloda",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "05/31/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Karan Bhai",
    businessName: "Shardha Fashion",
    mobile: "9924697140",
    salesExecutive: "Rutu Patel",
    email: "karan bhai6712@gmail.com",
    city: "Hingoli",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "06/01/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Vijay",
    businessName: "International Spa",
    mobile: "9586810226",
    salesExecutive: "Rutu Patel",
    email: "vijay6812@gmail.com",
    city: "Satara",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "06/02/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Radhika  Biyani",
    businessName: "Ramas Haute Couture",
    mobile: "9016588555",
    salesExecutive: "Rutu Patel",
    email: "radhika  biyani6912@gmail.com",
    city: "Amravati",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "06/03/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Anand",
    businessName: "Faabiola Designer Studio",
    mobile: "9374049963",
    salesExecutive: "Rutu Patel",
    email: "anand7012@gmail.com",
    city: "Osmanabad",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "06/04/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Tarun",
    businessName: "Urban Queen Studio",
    mobile: "9377667964",
    salesExecutive: "Rutu Patel",
    email: "tarun7112@gmail.com",
    city: "Pandharpur",
    leadSource: "IndiaMART",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "06/05/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Rajkumar Bhai",
    businessName: "Ambika Electronics",
    mobile: "9998086006",
    salesExecutive: "Rutu Patel",
    email: "rajkumar bhai7212@gmail.com",
    city: "Jaipur",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "06/06/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Ratna",
    businessName: "Manmohak Beauty Parlour",
    mobile: "8320485369",
    salesExecutive: "Rutu Patel",
    email: "ratna7312@gmail.com",
    city: "Jodhpur",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "06/07/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sagar Bhai",
    businessName: "Sagar Unisex Enterprise (Navsari)",
    mobile: "9601757743",
    salesExecutive: "Rutu Patel",
    email: "sagar bhai7412@gmail.com",
    city: "Kota",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "06/08/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Kishansingh",
    businessName: "Shreeji Bakery And Cafe",
    mobile: "8758214857",
    salesExecutive: "Rutu Patel",
    email: "kishansingh7512@gmail.com",
    city: "Udaipur",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "06/09/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sharatbhai",
    businessName: "James Hair Enterprise",
    mobile: "9714739740",
    salesExecutive: "Rutu Patel",
    email: "sharatbhai7612@gmail.com",
    city: "Rajkot",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "06/10/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Dinesh Bhai",
    businessName: "Viable Unisex Enterprise",
    mobile: "9974276535",
    salesExecutive: "Rutu Patel",
    email: "dinesh bhai7712@gmail.com",
    city: "Chittorghar",
    leadSource: "IndiaMART",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "06/11/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Avnish Bhai",
    businessName: "Sparten",
    mobile: "9898066770",
    salesExecutive: "Rutu Patel",
    email: "avnish bhai7812@gmail.com",
    city: "Ahmedabad",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "06/12/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Ganesh",
    businessName: "Serenity Spa",
    mobile: "9099145444",
    salesExecutive: "Rutu Patel",
    email: "ganesh7912@gmail.com",
    city: "Sirohi",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "06/13/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Chintan",
    businessName: "Crussh",
    mobile: "9099622139",
    salesExecutive: "Rutu Patel",
    email: "chintan8012@gmail.com",
    city: "Balasinor",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "06/14/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Narendrasingh",
    businessName: "Tip Top",
    mobile: "7435044536",
    salesExecutive: "Rutu Patel",
    email: "narendrasingh8112@gmail.com",
    city: "Neem Ka Thana",
    leadSource: "IndiaMART",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "06/15/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sameer",
    businessName: "Hammam Spa",
    mobile: "9099175555",
    salesExecutive: "Rutu Patel",
    email: "sameer8212@gmail.com",
    city: "Kishangarh",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "06/16/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Kundan",
    businessName: "Kundan Mobile Shop",
    mobile: "7405304186",
    salesExecutive: "Rutu Patel",
    email: "kundan8312@gmail.com",
    city: "Bikaner",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "06/17/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Manisha",
    businessName: "The Aurum Spa",
    mobile: "9099144347",
    salesExecutive: "Rutu Patel",
    email: "manisha8412@gmail.com",
    city: "Beawar",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "06/18/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Jeet",
    businessName: "Magnolia",
    mobile: "9662924417",
    salesExecutive: "Rutu Patel",
    email: "jeet8512@gmail.com",
    city: "Sheojang",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "06/19/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Nishant",
    businessName: "Gangaur",
    mobile: "9924422268",
    salesExecutive: "Rutu Patel",
    email: "nishant8612@gmail.com",
    city: "Sheoganj",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "06/20/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Lalbhai",
    businessName: "Pratham Mobile",
    mobile: "9662486652",
    salesExecutive: "Rutu Patel",
    email: "lalbhai8712@gmail.com",
    city: "Bharatpur",
    leadSource: "IndiaMART",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "06/21/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Bhadrik Patel",
    businessName: "Beauty Plus Cosmetic",
    mobile: "9909600791",
    salesExecutive: "Rutu Patel",
    email: "bhadrik patel8812@gmail.com",
    city: "Churu",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "06/22/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Pravin",
    businessName: "Decent Electronic",
    mobile: "9429148021",
    salesExecutive: "Rutu Patel",
    email: "pravin8912@gmail.com",
    city: "Sriganganagar",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "06/23/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Not Given",
    businessName: "The Optical Lab",
    mobile: "8866777743",
    salesExecutive: "Rutu Patel",
    email: "not given9012@gmail.com",
    city: "Bhilwara",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "06/24/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Rakesh Bhai",
    businessName: "K3Enterprise",
    mobile: "9075661001",
    salesExecutive: "Rutu Patel",
    email: "rakesh bhai9112@gmail.com",
    city: "Hanumangh",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "06/25/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Jagruti",
    businessName: "Yash Mobile",
    mobile: "8780956347",
    salesExecutive: "Rutu Patel",
    email: "jagruti9212@gmail.com",
    city: "Barmer",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "06/26/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Aayugbhai",
    businessName: "Zoomer Enterprice",
    mobile: "9725103911",
    salesExecutive: "Rutu Patel",
    email: "aayugbhai9312@gmail.com",
    city: "Ahmedabad",
    leadSource: "IndiaMART",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "06/27/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sangita Ben",
    businessName: "Khushbo Beauty Parlour",
    mobile: "9624665551",
    salesExecutive: "Rutu Patel",
    email: "sangita ben9412@gmail.com",
    city: "Mumbai",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "06/28/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Bhumi",
    businessName: "The Zodiac Spa",
    mobile: "9879660770",
    salesExecutive: "Rutu Patel",
    email: "bhumi9512@gmail.com",
    city: "Delhi",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "06/29/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Rajeev Bhai",
    businessName: "The Spa Lounge",
    mobile: "6206688931",
    salesExecutive: "Rutu Patel",
    email: "rajeev bhai9612@gmail.com",
    city: "Chennai",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "06/30/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Kirti Ben",
    businessName: "The Sumans Hair & Beauty Spaloon (Navsari)",
    mobile: "9687340175",
    salesExecutive: "Rutu Patel",
    email: "kirti ben9712@gmail.com",
    city: "Surat",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "07/01/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Umesh Jotangiya & Ashok",
    businessName: "Lady Care Enterprise (9033123425)",
    mobile: "9033123424",
    salesExecutive: "Rutu Patel",
    email: "umesh jotangiya & ashok9812@gmail.com",
    city: "Ahmedabad",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "07/02/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Juned",
    businessName: "Top 10 Spa",
    mobile: "7984157646",
    salesExecutive: "Rutu Patel",
    email: "juned9912@gmail.com",
    city: "Pune",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "07/03/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Jayendra Desai",
    businessName: "Fashion Ritmo",
    mobile: "9725868790",
    salesExecutive: "Rutu Patel",
    email: "jayendra desai10012@gmail.com",
    city: "Jaipur",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "07/04/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Naresh",
    businessName: "Angel Spa",
    mobile: "9099754122",
    salesExecutive: "Rutu Patel",
    email: "naresh10112@gmail.com",
    city: "Mohali",
    leadSource: "IndiaMART",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "07/05/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Manish Bhai",
    businessName: "Monalika Enterprise",
    mobile: "9276252374",
    salesExecutive: "Rutu Patel",
    email: "manish bhai10212@gmail.com",
    city: "Rajkot",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "07/06/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Dinesh Jain",
    businessName: "The Latest Fashion",
    mobile: "9624710790",
    salesExecutive: "Rutu Patel",
    email: "dinesh jain10312@gmail.com",
    city: "Lucknow",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "07/07/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Anand Mohan Ojha",
    businessName: "Nike",
    mobile: "9973904806",
    salesExecutive: "Rutu Patel",
    email: "anand mohan ojha10412@gmail.com",
    city: "Ahmedabad",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "07/08/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Bhavesh Shah",
    businessName: "Perfect Opticals",
    mobile: "9870000547",
    salesExecutive: "Rutu Patel",
    email: "bhavesh shah10512@gmail.com",
    city: "Mumbai",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "07/09/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sagar Bhai",
    businessName: "Tmcip Service ( Manorita Design Rf )",
    mobile: "7567562515",
    salesExecutive: "Rutu Patel",
    email: "sagar bhai10612@gmail.com",
    city: "Delhi",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "07/10/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Rahul",
    businessName: "A To Z Enterprise",
    mobile: "9879483788",
    salesExecutive: "Rutu Patel",
    email: "rahul10712@gmail.com",
    city: "Chennai",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "07/11/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sachin",
    businessName: "New Kheteshwar",
    mobile: "8209730750",
    salesExecutive: "Rutu Patel",
    email: "sachin10812@gmail.com",
    city: "Surat",
    leadSource: "IndiaMART",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "07/12/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Avinash",
    businessName: "Bhatia",
    mobile: "726509844",
    salesExecutive: "Rutu Patel",
    email: "avinash10912@gmail.com",
    city: "Ahmedabad",
    leadSource: "Linkedin",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "07/13/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Priti",
    businessName: "Mahek Enterprise And Academy",
    mobile: "9825521958",
    salesExecutive: "Rutu Patel",
    email: "priti11012@gmail.com",
    city: "Pune",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "07/14/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Kunal",
    businessName: "Shri Adeshwar Mobile",
    mobile: "8734934144",
    salesExecutive: "Rutu Patel",
    email: "kunal11112@gmail.com",
    city: "Jaipur",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "07/15/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Manishbhai",
    businessName: "Unique Enterprise",
    mobile: "9033377000",
    salesExecutive: "Rutu Patel",
    email: "manishbhai11212@gmail.com",
    city: "Mohali",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "07/16/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Nil",
    businessName: "Nilu Beauty Parlour",
    mobile: "9998077272",
    salesExecutive: "Rutu Patel",
    email: "nil11312@gmail.com",
    city: "Rajkot",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "07/17/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Rusabh Bhai",
    businessName: "Rushbh Mobile Care",
    mobile: "9824066770",
    salesExecutive: "Rutu Patel",
    email: "rusabh bhai11412@gmail.com",
    city: "Lucknow",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "07/18/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Noor",
    businessName: "Noor Optic",
    mobile: "9157864111",
    salesExecutive: "Rutu Patel",
    email: "noor11512@gmail.com",
    city: "Delhi",
    leadSource: "IndiaMART",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "07/19/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Asha Patel",
    businessName: "Freezy Enterprise ( Navsari)",
    mobile: "9925256572",
    salesExecutive: "Rutu Patel",
    email: "asha patel11612@gmail.com",
    city: "Ahmedabad",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "07/20/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Devyani Patel",
    businessName: "The Pink Palace (She Knows Sparsh - Nayna Ben)",
    mobile: "9278151152",
    salesExecutive: "Rutu Patel",
    email: "devyani patel11712@gmail.com",
    city: "Pune",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "07/21/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sandeep",
    businessName: "Hair Craft Enterprise",
    mobile: "9974726245",
    salesExecutive: "Rutu Patel",
    email: "sandeep11812@gmail.com",
    city: "Chennai",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "07/22/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Bina",
    businessName: "Vaishnavi",
    mobile: "7069040506",
    salesExecutive: "Rutu Patel",
    email: "bina11912@gmail.com",
    city: "Ahmedabad",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "07/23/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Nikunaj Bhai",
    businessName: "Italian Bekry",
    mobile: "9662542385",
    salesExecutive: "Rutu Patel",
    email: "nikunaj bhai12012@gmail.com",
    city: "Mumbai",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "07/24/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Dipti",
    businessName: "Beauty Point",
    mobile: "9879578182",
    salesExecutive: "Rutu Patel",
    email: "dipti12112@gmail.com",
    city: "Delhi",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "07/25/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Pranavbhai",
    businessName: "Khodiyar Dairy",
    mobile: "9106685504",
    salesExecutive: "Rutu Patel",
    email: "pranavbhai12212@gmail.com",
    city: "Chennai",
    leadSource: "IndiaMART",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "07/26/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Raj Bhai",
    businessName: "La Bella Hamam",
    mobile: "7567881880",
    salesExecutive: "Rutu Patel",
    email: "raj bhai12312@gmail.com",
    city: "Surat",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "07/27/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Jigar Bhai",
    businessName: "Navkar Communication",
    mobile: "6355148844",
    salesExecutive: "Rutu Patel",
    email: "jigar bhai12412@gmail.com",
    city: "Ahmedabad",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "07/28/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Gautam Bhai",
    businessName: "The South Bull Dosa",
    mobile: "9106972699",
    salesExecutive: "Rutu Patel",
    email: "gautam bhai12512@gmail.com",
    city: "Pune",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "07/29/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Anandbhai",
    businessName: "Avsar Jewellers",
    mobile: "9913339900",
    salesExecutive: "Rutu Patel",
    email: "anandbhai12612@gmail.com",
    city: "Jaipur",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "07/30/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sanjay Bhai",
    businessName: "Elvin Unisex Enterprise",
    mobile: "9173580471",
    salesExecutive: "Rutu Patel",
    email: "sanjay bhai12712@gmail.com",
    city: "Mohali",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "07/31/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Gaurav Bhai",
    businessName: "Prince Hair Enterprise",
    mobile: "9913157682",
    salesExecutive: "Rutu Patel",
    email: "gaurav bhai12812@gmail.com",
    city: "Rajkot",
    leadSource: "IndiaMART",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "08/01/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Narendra Patil",
    businessName: "Ganesh Mobile",
    mobile: "9726548783",
    salesExecutive: "Rutu Patel",
    email: "narendra patil12912@gmail.com",
    city: "Lucknow",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "08/02/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Jakky Sir",
    businessName: "Sivas Coffee",
    mobile: "9099772929",
    salesExecutive: "Rutu Patel",
    email: "jakky sir13012@gmail.com",
    city: "Ahmedabad",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "08/03/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Rishabh Gaud",
    businessName: "Coffee King",
    mobile: "7043897076",
    salesExecutive: "Rutu Patel",
    email: "rishabh gaud13112@gmail.com",
    city: "Mumbai",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "08/04/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Revat Bhai",
    businessName: "Krishna Optical",
    mobile: "7818819266",
    salesExecutive: "Rutu Patel",
    email: "revat bhai13212@gmail.com",
    city: "Delhi",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "08/05/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Visvash Soni",
    businessName: "T Shirt Studio",
    mobile: "9033321069",
    salesExecutive: "Rutu Patel",
    email: "visvash soni13312@gmail.com",
    city: "Chennai",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "08/06/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Jenish Bhai",
    businessName: "Coolma Health Care( Ref Rakesh Bhai)",
    mobile: "8460002101",
    salesExecutive: "Rutu Patel",
    email: "jenish bhai13412@gmail.com",
    city: "Surat",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "08/07/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Vaibhavi",
    businessName: "Mrs Beauty And Care",
    mobile: "957466675",
    salesExecutive: "Rutu Patel",
    email: "vaibhavi13512@gmail.com",
    city: "Ahmedabad",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "08/08/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Raja Bhai",
    businessName: "Mobile Studio",
    mobile: "7990089831",
    salesExecutive: "Rutu Patel",
    email: "raja bhai13612@gmail.com",
    city: "Pune",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "08/09/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Kashyap Bhai",
    businessName: "Gayatri Mobile",
    mobile: "8141319229",
    salesExecutive: "Rutu Patel",
    email: "kashyap bhai13712@gmail.com",
    city: "Jaipur",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "08/10/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Siddharth Bhai",
    businessName: "Madhur Electronics",
    mobile: "9099498498",
    salesExecutive: "Rutu Patel",
    email: "siddharth bhai13812@gmail.com",
    city: "Mohali",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "08/11/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Tejas Bhai",
    businessName: "Aashtha Raymond",
    mobile: "9723986519",
    salesExecutive: "Rutu Patel",
    email: "tejas bhai13912@gmail.com",
    city: "Rajkot",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "08/12/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Vipul Bhai",
    businessName: "S S Hair Studio",
    mobile: "8980390395",
    salesExecutive: "Rutu Patel",
    email: "vipul bhai14012@gmail.com",
    city: "Lucknow",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "08/13/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Kirti Ben",
    businessName: "Top Style Parlour ( Navsari )",
    mobile: "8866778424",
    salesExecutive: "Rutu Patel",
    email: "kirti ben14112@gmail.com",
    city: "Delhi",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "08/14/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Hemali Ben",
    businessName: "Hemali Beauty Parlour ( Navsari)",
    mobile: "9924307157",
    salesExecutive: "Rutu Patel",
    email: "hemali ben14212@gmail.com",
    city: "Ahmedabad",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "08/15/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Bhavik Shah",
    businessName: "Antrang",
    mobile: "9173344444",
    salesExecutive: "Rutu Patel",
    email: "bhavik shah14312@gmail.com",
    city: "Pune",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "08/01/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Tejas Patel",
    businessName: "La Pizza Treno",
    mobile: "8347178000",
    salesExecutive: "Rutu Patel",
    email: "tejas patel14412@gmail.com",
    city: "Chennai",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "08/02/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Kamlesh",
    businessName: "Honey Herbal Spa",
    mobile: "9924406676",
    salesExecutive: "Rutu Patel",
    email: "kamlesh14512@gmail.com",
    city: "Pune",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "08/03/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Nilu",
    businessName: "Nilu Beauty Parlour",
    mobile: "9898644527",
    salesExecutive: "Rutu Patel",
    email: "nilu14612@gmail.com",
    city: "Nagpur",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "08/04/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sonika Bhingradiya",
    businessName: "Sweet Stitches Boutique",
    mobile: "8141183868",
    salesExecutive: "Rutu Patel",
    email: "sonika bhingradiya14712@gmail.com",
    city: "Nashik",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "08/05/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Mustaf Bhau",
    businessName: "Casuals For Men",
    mobile: "7778896333",
    salesExecutive: "Rutu Patel",
    email: "mustaf bhau14812@gmail.com",
    city: "Aurangabad",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "08/06/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Abhishek Bhai",
    businessName: "Insta Fresh",
    mobile: "9904824238",
    salesExecutive: "Rutu Patel",
    email: "abhishek bhai14912@gmail.com",
    city: "Mumbai",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "08/07/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Daksha",
    businessName: "Feather Touch Beauty Parlour",
    mobile: "9374413538",
    salesExecutive: "Rutu Patel",
    email: "daksha15012@gmail.com",
    city: "Dombivli",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "08/08/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Heta",
    businessName: "Heetu Spa",
    mobile: "9574764159",
    salesExecutive: "Rutu Patel",
    email: "heta15112@gmail.com",
    city: "Sahada",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "08/09/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sharma Jack",
    businessName: "Head Quarters Unisex Hair And Cosmetic Studio",
    mobile: "9537591424",
    salesExecutive: "Rutu Patel",
    email: "sharma jack15212@gmail.com",
    city: "Jamner",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "08/10/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Parag Bhai",
    businessName: "Sal Line Saloon Katargam",
    mobile: "9375267500",
    salesExecutive: "Rutu Patel",
    email: "parag bhai15312@gmail.com",
    city: "Yavatmal",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "08/11/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Santosh",
    businessName: "Sukun Family Spaloon",
    mobile: "9099757971",
    salesExecutive: "Rutu Patel",
    email: "santosh15412@gmail.com",
    city: "Taloda",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "08/12/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Ravi Bhai",
    businessName: "Dosa King",
    mobile: "9773187762",
    salesExecutive: "Rutu Patel",
    email: "ravi bhai15512@gmail.com",
    city: "Hingoli",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "08/13/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Hetal Ben",
    businessName: "Hetal Beauty Parlour",
    mobile: "7600022477",
    salesExecutive: "Rutu Patel",
    email: "hetal ben15612@gmail.com",
    city: "Satara",
    leadSource: "Facebook",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "08/14/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Kirit",
    businessName: "Krishna Mobile Store",
    mobile: "9157276768",
    salesExecutive: "Rutu Patel",
    email: "kirit15712@gmail.com",
    city: "Amravati",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "08/15/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Bhavesh Patil",
    businessName: "Gym",
    mobile: "7698232494",
    salesExecutive: "Rutu Patel",
    email: "bhavesh patil15812@gmail.com",
    city: "Osmanabad",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "08/01/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Jigar Bhai",
    businessName: "Girnar Selection",
    mobile: "9898538795",
    salesExecutive: "Rutu Patel",
    email: "jigar bhai15912@gmail.com",
    city: "Pandharpur",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "08/02/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Pukhrajbhai",
    businessName: "Pinky Collection",
    mobile: "9909907181",
    salesExecutive: "Rutu Patel",
    email: "pukhrajbhai16012@gmail.com",
    city: "Kavathe Mahankal",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "08/03/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Mayak Bhai",
    businessName: "Harikrishna Jwellers",
    mobile: "9408453728",
    salesExecutive: "Rutu Patel",
    email: "mayak bhai16112@gmail.com",
    city: "Thane",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "08/04/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Hemin Shah",
    businessName: "Bijali",
    mobile: "9979592195",
    salesExecutive: "Rutu Patel",
    email: "hemin shah16212@gmail.com",
    city: "Delhi",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "08/05/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Vinodbhai",
    businessName: "Home Trends",
    mobile: "9898050305",
    salesExecutive: "Rutu Patel",
    email: "vinodbhai16312@gmail.com",
    city: "Surat",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "08/06/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Ishan",
    businessName: "Ishan Selection",
    mobile: "8320728559",
    salesExecutive: "Rutu Patel",
    email: "ishan16412@gmail.com",
    city: "Pune",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "08/07/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Rakesh Bhai",
    businessName: "Sayoni Sarees Shop",
    mobile: "9898044147",
    salesExecutive: "Rutu Patel",
    email: "rakesh bhai16512@gmail.com",
    city: "Nagpur",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "08/08/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Tulsi",
    businessName: "Natural Sweets",
    mobile: "9662246778",
    salesExecutive: "Rutu Patel",
    email: "tulsi16612@gmail.com",
    city: "Nashik",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "08/09/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Dimpal",
    businessName: "Dimpall Tailor",
    mobile: "9099923269",
    salesExecutive: "Rutu Patel",
    email: "dimpal16712@gmail.com",
    city: "Aurangabad",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "08/10/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Nikesh",
    businessName: "E Wealth Solution",
    mobile: "9408221735",
    salesExecutive: "Rutu Patel",
    email: "nikesh16812@gmail.com",
    city: "Mumbai",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "08/11/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Deep",
    businessName: "Zeel Enterprise",
    mobile: "6356667888",
    salesExecutive: "Rutu Patel",
    email: "deep16912@gmail.com",
    city: "Dombivli",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "08/12/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Fahadbhai",
    businessName: "Try Me",
    mobile: "8128100210",
    salesExecutive: "Rutu Patel",
    email: "fahadbhai17012@gmail.com",
    city: "Sahada",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "08/13/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Raj",
    businessName: "Mr. Cafe",
    mobile: "9274593745",
    salesExecutive: "Rutu Patel",
    email: "raj17112@gmail.com",
    city: "Jamner",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "08/14/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Jitendra",
    businessName: "Spa Space",
    mobile: "8238482121",
    salesExecutive: "Rutu Patel",
    email: "jitendra17212@gmail.com",
    city: "Yavatmal",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Close Lead",
    createdDate: "08/15/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Jalpa",
    businessName: "Atmosphere Enterprise",
    mobile: "8460600035",
    salesExecutive: "Rutu Patel",
    email: "jalpa17312@gmail.com",
    city: "Taloda",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "08/01/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sweety",
    businessName: "Poonam Bridal Studio",
    mobile: "8980927903",
    salesExecutive: "Rutu Patel",
    email: "sweety17412@gmail.com",
    city: "Hingoli",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "08/02/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Alpesh Bhai",
    businessName: "Coiffure Unisex Enterprise",
    mobile: "9909430180",
    salesExecutive: "Rutu Patel",
    email: "alpesh bhai17512@gmail.com",
    city: "Satara",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "08/03/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Raghu",
    businessName: "Dryfruit House",
    mobile: "9737860099",
    salesExecutive: "Rutu Patel",
    email: "raghu17612@gmail.com",
    city: "Amravati",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "08/04/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Kishor Bhai",
    businessName: "Dharmesh Hair Art",
    mobile: "9879050381",
    salesExecutive: "Rutu Patel",
    email: "kishor bhai17712@gmail.com",
    city: "Osmanabad",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "08/05/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Krunal",
    businessName: "Krunal Mobile",
    mobile: "8460282845",
    salesExecutive: "Rutu Patel",
    email: "krunal17812@gmail.com",
    city: "Pandharpur",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "New",
    createdDate: "08/06/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Sameena Master",
    businessName: "Beauty Bliss Enterprise",
    mobile: "9152570367",
    salesExecutive: "Rutu Patel",
    email: "sameena master17912@gmail.com",
    city: "Jaipur",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "08/07/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Deepak",
    businessName: "Happy Family Saloon",
    mobile: "7486986683",
    salesExecutive: "Rutu Patel",
    email: "deepak18012@gmail.com",
    city: "Jodhpur",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "08/08/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Ajaybhai",
    businessName: "Laxmi Communication",
    mobile: "9898983486",
    salesExecutive: "Rutu Patel",
    email: "ajaybhai18112@gmail.com",
    city: "Kota",
    leadSource: "justdial",
    leadType: "Warm",
    currentStatus: "Interested",
    createdDate: "08/09/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Hemant Bhai Khemani",
    businessName: "Jiya Exclusive Kurties And Tops",
    mobile: "9624619209",
    salesExecutive: "Rutu Patel",
    email: "hemant bhai khemani18212@gmail.com",
    city: "Udaipur",
    leadSource: "Referral",
    leadType: "Warm",
    currentStatus: "Not Interested",
    createdDate: "08/10/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Ashok Bhai",
    businessName: "Real Enterprice",
    mobile: "9904552908",
    salesExecutive: "Rutu Patel",
    email: "ashok bhai18312@gmail.com",
    city: "Rajkot",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "08/11/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Jayesh Rathod",
    businessName: "Roopkala Hair Art",
    mobile: "8469866927",
    salesExecutive: "Rutu Patel",
    email: "jayesh rathod18412@gmail.com",
    city: "Chittorghar",
    leadSource: "Instagram",
    leadType: "Warm",
    currentStatus: "Negotiation",
    createdDate: "08/12/2021",
    updatedDate: "12/08/2021",
  },
  {
    ownerName: "Aakruti",
    businessName: "Aakruti Fashion Studio",
    mobile: "9825322327",
    salesExecutive: "Rutu Patel",
    email: "aakruti18512@gmail.com",
    city: "Chittorghar",
    leadSource: "Website",
    leadType: "Warm",
    currentStatus: "Contacted",
    createdDate: "08/13/2021",
    updatedDate: "12/08/2021",
  },
];
