export const orderMgtTblData=[
    {
      "date": "08/02/2021",
      "invoiceNumber": "1211196",
      "customerName": "Jagdish Kohli",
      "businessName": "Alessiya Enterprise",
      "productName": "Combo Pack",
      "leadSource": "Facebook",
      "quantity": "1",
      "totalAmount": "10000",
      "paymentStatus": "Received"
    },
    {
      "date": "08/02/2021",
      "invoiceNumber": "1211197",
      "customerName": "Giri Rajan",
      "businessName": "Aroma Wellness",
      "productName": "Renewal Pack",
      "leadSource": "Instagram",
      "quantity": "1",
      "totalAmount": "3000",
      "paymentStatus": "Pending"
    },
    {
      "date": "08/02/2021",
      "invoiceNumber": "1211198",
      "customerName": "Mahendra  Patel",
      "businessName": "Aashapura Mobile",
      "productName": "Subscription Pack",
      "leadSource": "Linkedin",
      "quantity": "1",
      "totalAmount": "3500",
      "paymentStatus": "Pending"
    },
    {
      "date": "08/02/2021",
      "invoiceNumber": "1211199",
      "customerName": "Rajan Rahane",
      "businessName": "Hp Technosoft",
      "productName": "Loyalty Pack",
      "leadSource": "Website",
      "quantity": "1",
      "totalAmount": "4000",
      "paymentStatus": "Received"
    },
    {
      "date": "08/02/2021",
      "invoiceNumber": "1211200",
      "customerName": "Nitin Ahuja",
      "businessName": "Shivam Solutions",
      "productName": "SMS Pack",
      "leadSource": "Website",
      "quantity": "1",
      "totalAmount": "2000",
      "paymentStatus": "Received"
    },
    {
      "date": "08/03/2021",
      "invoiceNumber": "1211201",
      "customerName": "Tanisha Yadav",
      "businessName": "Pixie Solutions",
      "productName": "Combo Pack",
      "leadSource": "Linkedin",
      "quantity": "1",
      "totalAmount": "10000",
      "paymentStatus": "Pending"
    },
    {
      "date": "08/03/2021",
      "invoiceNumber": "1211202",
      "customerName": "Sandip Ichani",
      "businessName": "Bhuvneshwar Traders",
      "productName": "Loyalty Pack",
      "leadSource": "Facebook",
      "quantity": "1",
      "totalAmount": "4000",
      "paymentStatus": "Pending"
    },
    {
      "date": "08/03/2021",
      "invoiceNumber": "1211203",
      "customerName": "Divya",
      "businessName": "Coco International",
      "productName": "Subscription Pack",
      "leadSource": "Linkedin",
      "quantity": "1",
      "totalAmount": "3500",
      "paymentStatus": "Received"
    },
    {
      "date": "08/04/2021",
      "invoiceNumber": "1211204",
      "customerName": "Anita",
      "businessName": "Shree Rang Traders",
      "productName": "Renewal Pack",
      "leadSource": "IndiaMART",
      "quantity": "1",
      "totalAmount": "3000",
      "paymentStatus": "Received"
    },
    {
      "date": "08/04/2021",
      "invoiceNumber": "1211205",
      "customerName": "Rakesh Bhai",
      "businessName": "Rushabh Mobile",
      "productName": "Combo Pack",
      "leadSource": "Website",
      "quantity": "1",
      "totalAmount": "10000",
      "paymentStatus": "Pending"
    },
    {
      "date": "08/04/2021",
      "invoiceNumber": "1211206",
      "customerName": "Harishbhai",
      "businessName": "Dragon Enterprise",
      "productName": "Renewal Pack",
      "leadSource": "justdial",
      "quantity": "1",
      "totalAmount": "3000",
      "paymentStatus": "Received"
    },
    {
      "date": "08/05/2021",
      "invoiceNumber": "1211207",
      "customerName": "Jayesh Bhai",
      "businessName": "Beblly",
      "productName": "Loyalty Pack",
      "leadSource": "Instagram",
      "quantity": "1",
      "totalAmount": "4000",
      "paymentStatus": "Received"
    },
    {
      "date": "08/05/2021",
      "invoiceNumber": "1211208",
      "customerName": "Nilesh Patel",
      "businessName": "Gayatri Electronics",
      "productName": "Subscription Pack",
      "leadSource": "Website",
      "quantity": "1",
      "totalAmount": "3500",
      "paymentStatus": "Pending"
    },
    {
      "date": "08/06/2021",
      "invoiceNumber": "1211209",
      "customerName": "Herikbhai",
      "businessName": "Advance Professional Solutions",
      "productName": "SMS Pack",
      "leadSource": "Facebook",
      "quantity": "1",
      "totalAmount": "2000",
      "paymentStatus": "Received"
    },
    {
      "date": "08/06/2021",
      "invoiceNumber": "1211210",
      "customerName": "Karan Bhai",
      "businessName": "Shardha Fashion",
      "productName": "SMS Pack",
      "leadSource": "Website",
      "quantity": "1",
      "totalAmount": "2000",
      "paymentStatus": "Received"
    },
    {
      "date": "08/07/2021",
      "invoiceNumber": "1211211",
      "customerName": "Bhumi",
      "businessName": "The Zodiac Traders",
      "productName": "Renewal Pack",
      "leadSource": "Instagram",
      "quantity": "1",
      "totalAmount": "3000",
      "paymentStatus": "Pending"
    },
    {
      "date": "08/09/2021",
      "invoiceNumber": "1211212",
      "customerName": "Kunal",
      "businessName": "Shri Adeshwar Mobile",
      "productName": "Loyalty Pack",
      "leadSource": "Facebook",
      "quantity": "1",
      "totalAmount": "4000",
      "paymentStatus": "Received"
    },
    {
      "date": "08/09/2021",
      "invoiceNumber": "1211213",
      "customerName": "Nil",
      "businessName": "Nilu Beauty Enterprise",
      "productName": "SMS Pack",
      "leadSource": "justdial",
      "quantity": "1",
      "totalAmount": "2000",
      "paymentStatus": "Received"
    },
    {
      "date": "08/09/2021",
      "invoiceNumber": "1211214",
      "customerName": "Noor",
      "businessName": "Noor Optic Solutions",
      "productName": "Subscription Pack",
      "leadSource": "IndiaMART",
      "quantity": "1",
      "totalAmount": "3500",
      "paymentStatus": "Pending"
    },
    {
      "date": "08/09/2021",
      "invoiceNumber": "1211215",
      "customerName": "Sandeep",
      "businessName": "Craft Decor",
      "productName": "SMS Pack",
      "leadSource": "Referral",
      "quantity": "1",
      "totalAmount": "2000",
      "paymentStatus": "Received"
    },
    {
      "date": "08/10/2021",
      "invoiceNumber": "1211216",
      "customerName": "Rishabh Gaud",
      "businessName": "Coffee King",
      "productName": "Subscription Pack",
      "leadSource": "Referral",
      "quantity": "1",
      "totalAmount": "3500",
      "paymentStatus": "Received"
    },
    {
      "date": "08/10/2021",
      "invoiceNumber": "1211217",
      "customerName": "Revat Bhai",
      "businessName": "Krishna Optical Solutions",
      "productName": "Renewal Pack",
      "leadSource": "Instagram",
      "quantity": "1",
      "totalAmount": "3000",
      "paymentStatus": "Received"
    },
    {
      "date": "08/11/2021",
      "invoiceNumber": "1211218",
      "customerName": "Vipul Bhai",
      "businessName": "S S Studio",
      "productName": "Subscription Pack",
      "leadSource": "Referral",
      "quantity": "1",
      "totalAmount": "3500",
      "paymentStatus": "Pending"
    },
    {
      "date": "08/11/2021",
      "invoiceNumber": "1211219",
      "customerName": "Kirti Ben",
      "businessName": "Top Style Enterprise",
      "productName": "Loyalty Pack",
      "leadSource": "Facebook",
      "quantity": "1",
      "totalAmount": "4000",
      "paymentStatus": "Received"
    },
    {
      "date": "08/12/2021",
      "invoiceNumber": "1211220",
      "customerName": "Nilu",
      "businessName": "Nilu Enterprise",
      "productName": "SMS Pack",
      "leadSource": "justdial",
      "quantity": "1",
      "totalAmount": "2000",
      "paymentStatus": "Pending"
    },
    {
      "date": "08/12/2021",
      "invoiceNumber": "1211221",
      "customerName": "Sharma Jack",
      "businessName": "Head Quarters Cosmetic Studio",
      "productName": "Subscription Pack",
      "leadSource": "Referral",
      "quantity": "1",
      "totalAmount": "3500",
      "paymentStatus": "Received"
    },
    {
      "date": "08/13/2021",
      "invoiceNumber": "1211222",
      "customerName": "Hetal Ben",
      "businessName": "Hetal Beauty Solutions",
      "productName": "SMS Pack",
      "leadSource": "Facebook",
      "quantity": "1",
      "totalAmount": "2000",
      "paymentStatus": "Pending"
    },
    {
      "date": "08/13/2021",
      "invoiceNumber": "1211223",
      "customerName": "Pukhrajbhai",
      "businessName": "Pinky Collection",
      "productName": "Loyalty Pack",
      "leadSource": "Instagram",
      "quantity": "1",
      "totalAmount": "4000",
      "paymentStatus": "Pending"
    },
    {
      "date": "08/13/2021",
      "invoiceNumber": "1211224",
      "customerName": "Hemin Shah",
      "businessName": "Bijali",
      "productName": "Subscription Pack",
      "leadSource": "Referral",
      "quantity": "1",
      "totalAmount": "3500",
      "paymentStatus": "Received"
    },
    {
      "date": "08/14/2021",
      "invoiceNumber": "1211225",
      "customerName": "Jitendra",
      "businessName": "Space Pvt Ltd",
      "productName": "Renewal Pack",
      "leadSource": "Referral",
      "quantity": "1",
      "totalAmount": "3000",
      "paymentStatus": "Received"
    }
  ]